### ISSUE TITLE
New Plans are Upload+Download

### ISSUE THREAD

**Issue by troystanway** [minusInfinite/NuSkopeUsage-Rainmeter#1]
Hi,

Great project, been using it for a while, but now I'm on their new plan which is Upload+Download and the usage meter doesn't aggregate the data usage, which means its giving me the wrong numbers.

Can we alter the variables to fix this?

**Comment by minusInfinite** [comment]
I Troy
Thanks for that hadn't realised they had changed that. I'll look into getting the meter updated as soon as possible as looking at my own api feed they changed mine as well.

**Comment by minusInfinite** [comment]
Hi Troy

This should be fixed for https://github.com/minusInfinite/NuSkopeUsage-Rainmeter/releases/tag/0.2

Please let me know how you go.

**Comment by troystanway** [comment]
I just tried it, works perfectly! Thanks
